In [107]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math

In [108]:
data = pd.read_csv('/home/surbhi/deadline_project/data_26_nov_2019/driver type/driver2/event_type/speed_breaker/TWO_WHEELER_MOUNTER_26_11_2019-06_32_10_ONEPLUS A3003_150/kalman_impli.csv')

In [109]:
data.drop(0, inplace=True)

In [110]:
data.head(10)

,Unnamed: 0,x,y,z,latitude,longitude,bearing,accuracy,light,timestamp,Unnamed: 9,y1,z1
1,1,-2.051135e-08,-1.776357e-15,9.957118,23.556658,87.307888,98.573196,3.216,0,30664423,0,-1.758769e-15,9.858534
2,2,2.421471e-01,8.784359e-01,10.412949,23.556658,87.307888,98.573196,3.216,0,30664452,0,4.372545e-01,10.134502
3,3,-2.030194e-01,-5.179680e-01,8.769594,23.556658,87.307888,98.573196,3.216,0,30664486,0,1.193718e-01,9.680283
4,4,-2.296630e-08,-1.332268e-15,9.541734,23.556658,87.307888,98.573196,3.216,0,30664493,0,8.949860e-02,9.645610
5,5,5.333429e-01,1.129868e+00,10.587949,23.556658,87.307888,98.573196,3.216,0,30664523,0,2.984063e-01,9.834833
6,6,2.289383e-08,0.000000e+00,9.739694,23.556658,87.307888,98.573196,3.216,0,30664539,0,2.482992e-01,9.818858
7,7,5.906312e-01,-5.928309e-01,8.548448,23.556658,87.307888,98.573196,3.216,0,30664562,0,1.267505e-01,9.635276
8,8,-1.562939e-08,-1.332268e-15,9.951151,23.556658,87.307888,98.573196,3.216,0,30664574,0,1.106502e-01,9.675399
9,9,6.760155e-01,9.547005e-01,10.768209,23.556658,87.307888,98.573196,3.216,0,30664600,1,2.064446e-01,9.799426
10,10,2.959609e-08,-8.881784e-16,9.504625,23.556658,87.307888,98.573196,3.216,0,30664608,0,1.852362e-01,9.769141

In [111]:
max_threshold = data['z1'].max()
max_threshold

10.48706717426673

In [112]:
min_threshold = data['z1'].min()
min_threshold

7.8879523641054154

In [113]:
# Dividing the data into windows of size 100
windows = []

last = len(data) // 100

for i in range(last):
    windows.append(data.iloc[i*100:i*100+100])
    
windows.append(data.iloc[last*100:-1])

In [114]:
j=1
for i in windows:
    local_max = i['z1'].max()
    local_min = i['z1'].min()
    if((max_threshold-1)<local_max<=max_threshold  and (min_threshold+1)<local_min<=min_threshold):
        i.to_csv('/home/surbhi/deadline_project/data_26_nov_2019/driver type/driver2/event_type/speed_breaker/TWO_WHEELER_MOUNTER_26_11_2019-06_32_10_ONEPLUS A3003_150/event_detect/event'+str(j)+'.csv')
        j=j+1